modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
issueTrackerURL=""

[[mods]] #mandatory
modId="simple_spikes" #mandatory
version="1.19.2-1.0.0" #mandatory
displayName="Simple Spikes" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-spikes"
logoFile="logo.png" #optional
authors="ISenseHostility" #optional
description='''
Simple Spikes for simple mob farming.
    '''

[[dependencies.simple_spikes]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.simple_spikes]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2, 1.20)"
ordering="NONE"
side="BOTH"